### PR TITLE
several firmware magics

### PR DESCRIPTION
**Pull request by M1cha**
just a few file formats used by Android firmware/bootloader developers

### CODE REVIEW

**Comment by M1cha** [comment]
I just noticed that there is a warning:
```
WARNING: Signature '0     string     __UTAG_HEAD__   Motorola UTAGS' is a self-overlapping signature!
```
what does cause this?  are '__' treated in a special way?

**Comment by M1cha** [comment]
I fixed it by adding \x00 to the end

**Comment by M1cha** [comment]
Is there a way to do multi-line matches? i.e. the bootloader which parses the bootlogo gets matched because it contains the magic string.

I can do sth. like !0 but t hat will only prevent printing that specific field, not the whole thing.

**Comment by devttys0** [comment]
Yes, you can include additional validation to a signature using the `{invalid}` tag. A simple example would look something like this:

```
0   string    ABCD    Signature for ABCD file type,
>4 ulelong    x       file size: %d,
>4 ulelong    >1024   {invalid}  # ABCD files should never be larger than 1024 bytes
```

**Comment by M1cha** [comment]
thx, I update the Nexus magic definitions so they don't match the string tables anymore

**Pull request merged**
