### PR TITLE
Improve (U)EFI structures detection

### PR DESCRIPTION
**Pull request by Flameeyes**
After an interesting thread on Twitter with @theopolis and @LongSoft I ended up adding some more support for EFI structures identification.

### CODE REVIEW

**Comment by Flameeyes** [comment]
Note: I'm not sure if the magic format has to stay compatible with libmagic — if not I guess a "guid" type would be nice for things like this, but it might be a bit specific :)

**Comment by NikolajSchlej** [comment]
You can get a bit more GUIDs from here: https://github.com/LongSoft/UEFITool/blob/new_engine/common/ffs.h
I detect the volumes from their _FVH signature and filter out all of candidates with FvLength > 0xFFFFFFFF, Revision != 1 or 2 or Reserved != 0. This way the GUID can be anything and yet it detects almost all valid UEFI Firmware Volumes to date.

**Comment by Flameeyes** [comment]
Okay I followed Nikolaj's advice and added some more parsing and entries and simplified a few things here and there.

If there is a way to check against the remaining data size it would make things nicer, but already as it is, it avoids a number of false positives.

**Comment by Flameeyes** [comment]
Hmm I guess binwalk could use plugins based on UEFITool :) I'll check once I'm at a real PC ;)

**Pull request merged**
